language: python
python:
  - "2.7"
  - "3.4"
# command to install dependencies
install: "pip install -r requirements.txt"
# prepare files for test
before_script:
  - mkdir /tmp/test
  - touch /tmp/test/0
  - touch /tmp/test/1
# command to run tests
script: py.test